"use client";

import { Pencil, Plus, Trash2, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { adminApi, type Taxonomy } from "./admin-api";
import { EmptyState, ErrorBanner, LoadingState, SectionHeader } from "./admin-shell";
import styles from "./admin.module.css";

export function TaxonomyPanel({type}:{type:"categories"|"tags"}){const[data,setData]=useState<Taxonomy[]|null>(null);const[editing,setEditing]=useState<Taxonomy|null|undefined>(undefined);const[error,setError]=useState("");const load=useCallback(()=>adminApi<{data:Taxonomy[]}>(`/${type}`).then(body=>setData(body.data)).catch(e=>setError(e.message)),[type]);useEffect(()=>{void load()},[load]);
  const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError("");const values=Object.fromEntries(new FormData(event.currentTarget));try{await adminApi(`/${type}${editing?.id?`/${editing.id}`:""}`,{method:editing?.id?"PATCH":"POST",body:JSON.stringify(values)});setEditing(undefined);await load();}catch(e){setError((e as Error).message)}};
  const remove=async(item:Taxonomy)=>{if(!confirm(`Delete ${item.name}? Existing novel links will be removed.`))return;try{await adminApi(`/${type}/${item.id}`,{method:"DELETE"});await load();}catch(e){setError((e as Error).message)}};
  if(!data&&!error)return <LoadingState/>;return <><SectionHeader title={type==="categories"?"Categories":"Tags"} description={type==="categories"?"Primary genres used for catalog navigation.":"Independent labels used to describe novel themes."} action={<button className={styles.primaryButton} onClick={()=>setEditing(null)}><Plus size={16}/> Add {type==="categories"?"category":"tag"}</button>}/>{error?<ErrorBanner message={error}/>:null}{data?.length?<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Name</th><th>Slug</th><th>Novels</th><th aria-label="Actions"/></tr></thead><tbody>{data.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.slug}</td><td>{item._count?.novels??0}</td><td><div className={styles.actions}><button className={styles.iconButton} title="Edit" onClick={()=>setEditing(item)}><Pencil size={16}/></button><button className={styles.iconButton} title="Delete" onClick={()=>remove(item)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>:<EmptyState message={`No ${type} yet.`}/>} {editing!==undefined?<div className={styles.modalBackdrop} role="presentation"><form className={styles.modal} onSubmit={save}><div className={styles.modalHeader}><h2>{editing?"Edit":"Add"} {type==="categories"?"category":"tag"}</h2><button type="button" className={styles.iconButton} onClick={()=>setEditing(undefined)} aria-label="Close"><X size={18}/></button></div><div className={`${styles.modalBody} ${styles.formGrid}`}><div className={styles.field}><label htmlFor="tax-name">Name</label><input id="tax-name" name="name" defaultValue={editing?.name} required/></div><div className={styles.field}><label htmlFor="tax-slug">Slug</label><input id="tax-slug" name="slug" defaultValue={editing?.slug} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required/></div>{type==="categories"?<div className={styles.field}><label htmlFor="tax-icon">Icon key</label><input id="tax-icon" name="icon" defaultValue={editing?.icon??""}/></div>:null}</div><div className={styles.modalFooter}><button type="button" className={styles.secondaryButton} onClick={()=>setEditing(undefined)}>Cancel</button><button className={styles.primaryButton}>Save</button></div></form></div>:null}</>}
