export const recommendedNovelSlugs = [
  "after-i-leftbillionaire-ex-hunts-me-worldwide",
  "the-billionaires-bargain-bridescorned-heiress-strikes-back",
  "bracelet-of-lies",
  "thornes-redemption",
  "psis-asylum",
  "royal-secret-the-lycan-kings-bargain",
  "the-poison-in-his-kiss",
  "his-first-love-returned-during-my-pregnancy",
  "my-husband-sold-me-to-his-boss",
  "lunas-defective-redemption",
  "marked-by-the-enemy",
  "lunar-vow-of-scorned-blood",
  "contractual-hearts-the-billionaires-redemption",
  "rejected-luna-untamed-desire-of-the-lycan-alpha",
  "the-queen-returns-pampered-by-her-three-powerhouse-brothers",
  "the-diamond-identity",
  "scarlet-shield",
  "moonfire-eclipse-true-mate-prophecy",
  "psis-asylum",
  "bracelet-of-lies",
  "rebirth-the-crimson-vow",
  "my-weak-wife-is-a-real-goddess1",
  "scorned-ex-wife-queen-of-ashes",
  "throne-of-starlight-and-scars",
  "heartbreak-billionairehe-should-never-have-let-go",
  "chronicles-of-the-arcane-academy",
  "heirs-of-vengeance-the-ceos-little-cupids",
  "alphas-cursed-mate-the-rogue-heir",
  "taking-alpha-twins-away-after-divorce",
  "the-poison-in-his-kiss",
  "bound-by-blood-and-shadows",
  "my-billionaire-wifes-deadly-affair",
  "soulbound-whispers-of-the-fallen-temple",
  "veiled-in-emerald-temptation",
  "the-unwanted-daughters-alpha-king",
  "scarlet-resilience",
  "his-secret-heir-and-her-vengeance",
  "scalpel-and-moonlight",
  "crescent-bloodline-volcanic-throne",
  "too-late-for-regret-the-genius-heiress-who-shines",
  "veilborn",
  "beneath-the-executives-mask",
  "forbidden-heir",
  "abyssal-bonds",
  "sightless-redemption",
  "the-last-spirit-wolf",
  "rejected-by-the-alpha-claimed-by-the-pack",
  "veiled-vows-the-billionaires-vendetta",
  "embers-of-the-guilty",
  "rise-of-the-billionaires-runaway-bride",
  "tangled-vows",
  "reign-of-the-reborn-luna",
  "blood-born-fury",
  "bloodline-captive-russian-mafia-heirs",
  "thornes-redemption",
  "beneath-the-ceos-cold-embrace",
  "bets-and-bridal-veils",
  "scarlet-vows-sapphire-wounds",
  "phantoms-heir",
  "kings-captive-bloom",
  "echoes-of-the-feral",
  "bound-to-the-billionaires-heir",
  "ceos-ex-wife-strikes-back",
  "runaway-heiress-reborn-crushing-ceo-ex",
  "lunas-twin-alphas-curse-of-the-blood-moon",
  "bound-by-shadow-claimed-by-soul",
  "lunas-divine-mark",
  "royal-secret-the-lycan-kings-bargain",
  "the-billionaires-bargain-bridescorned-heiress-strikes-back",
  "shadows-of-the-reborn-luna",
  "crimson-vendettas",
  "after-i-leftbillionaire-ex-hunts-me-worldwide",
  "crimson-legacy",
  "keep-distance-mr-ceo",
  "blood-oath-vendetta"
] as const;

export const homeCategorySource = [
  { slug: "contemporary", name: "Contemporary", novels: ["sightless-redemption", "rise-of-the-billionaires-runaway-bride", "mistaken-midnight-with-the-ceo", "contractual-hearts-the-billionaires-redemption", "the-richest-billionaire-is-my-accidental-husband"] },
  { slug: "romance", name: "Romance", novels: ["crimson-vendettas", "veiled-in-emerald-temptation", "reign-of-the-reborn-luna", "taking-alpha-twins-away-after-divorce", "the-billionaires-bargain-bridescorned-heiress-strikes-back"] },
  { slug: "fantasy", name: "Fantasy", novels: ["veiled-in-emerald-temptation", "reign-of-the-reborn-luna", "the-billionaires-bargain-bridescorned-heiress-strikes-back", "his-secret-heir-and-her-vengeance", "phantoms-heir"] },
  { slug: "werewolf", name: "Werewolf", novels: ["taking-alpha-twins-away-after-divorce", "the-hidden-princess-at-all-boys-alpha-academy", "rejected-luna-untamed-desire-of-the-lycan-alpha", "between-ruin-and-resolve-my-ex-husbands-regret1", "moonfire-eclipse-true-mate-prophecy"] }
] as const;
